/**
 * Redux const
 */

export const TOGGLE_MENU = 'TOGGLE_MENU';
export const SET_HOME_PRODUCTOS = 'SET_HOME_PRODUCTOS';
export const SET_HOME_CATEGORIAS = 'SET_HOME_CATEGORIAS';
export const SET_LOADING_HOME_PRODUCTOS = 'SET_LOADING_HOME_PRODUCTOS';
export const SET_TOAST_ERROR = 'SET_TOAST_ERROR';
export const SET_SPINNER = 'SET_SPINNER';